- name: Add or update registry path
  hosts: 
  tasks:

    - name: Add registry path
      ansible.windows.win_regedit:
        path: HKCU:\Software\LeandroScardua
        name: test
        data: leandroscardua

    - name: Change default mouse trailing settings for new users
      ansible.windows.win_regedit:
        path: HKLM:\ANSIBLE\Control Panel\Mouse
        name: MouseTrails
        data: 10
        type: string
        state: present
        hive: C:\Users\Default\NTUSER.dat
