- name: Add or update registry path
  hosts: 
  tasks:

    - name: Add registry path
      ansible.windows.win_regedit:
        path: HKCU:\Software\LeandroScardua
        name: test
        data: leandroscardua

    - name: Change windows updates
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
        name: AU
        data: 1
        state: present
