- name: Install an Application with chocolatey
  hosts: 
  tasks:

    - name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
      win_chocolatey:
        name: chocolatey
        state: latest

    - name: Install Wireshark
      win_chocolatey:
        name: wireshark
        state: present
        version: '4.2.3'

    - name: Install multiple packages
      win_chocolatey:
        name:
        - slack
        - zoom
        - filezilla
        state: present
