- name: Install WWindows Updates
  hosts: 
  tasks: 

    - name: Set service startup mode to manual and ensure it is started (wuauserv)
      ansible.windows.win_service:
        name: wuauserv
        start_mode: manual
        state: started

    - name: Disable Automatic Windows Update via register
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: NoAutoUpdate
        data: "1"
        type: dword

    - name: Disable Automatic Windows Update via register
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: AUOptions
        data: "1"
        type: dword

    - name: Ensure WinRM starts when the system has settled and is ready to work reliably
      ansible.windows.win_service:
        name: WinRM
        start_mode: delayed

    - name: Install Servicing Stack Updates
      ansible.windows.win_updates:
        accept_list:
          - \d{4}-\d{2} Servicing Stack Update for Windows Server
        server_selection: windows_update
        reboot: true
        reboot_timeout: 3600
        state: installed
      register: windows_update_count_ssu

    - name: Install all security, critical, definition and defender Updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - Definition Updates
          - Microsoft Defender Antivirus
        server_selection: windows_update
        reboot: true
        reboot_timeout: 3600
        state: installed
      register: windows_update_count_all

    - name: Install Definition Updates and Security Updates
      ansible.windows.win_updates:
        category_names:
          - Definition Updates
          - Microsoft Defender Antivirus
        server_selection: windows_update
        state: installed
      register: windows_update_count_dus

    - name: Write log on events for audit purpose
      community.windows.win_eventlog_entry:
        log: Application
        source: Ansible
        entry_type: Information
        event_id: 0
        message: "{{ windows_update_count_dus.installed_update_count }} Defender and Definition Updates was installed by Ansible"
      when: windows_update_count_dus.installed_update_count > 0

    - name: Write log on events for audit purpose
      community.windows.win_eventlog_entry:
        log: Application
        source: Ansible
        entry_type: Information
        event_id: 0
        message: "{{ windows_update_count_all.installed_update_count }} Windows updates SSU was installed by Ansible"
      when: windows_update_count_ssu.installed_update_count > 0

    - name: Write log on events for audit purpose
      community.windows.win_eventlog_entry:
        log: Application
        source: Ansible
        entry_type: Information
        event_id: 0
        message: "{{ windows_update_count_all.installed_update_count }} Windows, Defender and Security Updates was installed by Ansible"
      when: windows_update_count_all.installed_update_count > 0

    - name: Set service startup mode to disabled and ensure it is stopped (wuauserv)
      ansible.windows.win_service:
        name: wuauserv
        start_mode: manual
        state: stopped
        force_dependent_services: true

    - name: Ensure that WinRM is auto start mode when the system has settled
      ansible.windows.win_service:
        name: WinRM
        start_mode: auto
        state: started

    - name: Show the output with the results
      ansible.builtin.debug:
        msg:
          - "Server Name: {{ ansible_hostname }}"
          - "OS version: {{ ansible_distribution }}"
          - "Pending Windows Updates: {{ windows_update_count_all.found_update_count }}"
          - "Pending Defender Updates: {{ windows_update_count_dus.found_update_count }}"
          - "Pending Servicing Stack Updates: {{ windows_update_count_ssu.found_update_count }}"
          - "Reboot required for Windows Updates: {{ windows_update_count_all.reboot_required }}"
          - "Installed Defender Updates: {{ windows_update_count_dus.installed_update_count }}"
          - "Installed Windows Updates: {{ windows_update_count_all.installed_update_count }}"
          - "Installed Servicing Stack Updates: {{ windows_update_count_ssu.installed_update_count }}"
