- name: Search for Updates on Ansible
  hosts: 
  tasks:
    - name: 
      ansible.windows.win_package:
        path: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.4.8/npp.8.4.8.Installer.exe
        state: present
        arguments: /S
