- name: Search for Updates on Ansible
  hosts: 
  tasks:
    - name: Install IIS Web-Server with sub features and management tools
      ansible.windows.win_feature:
        name: Web-Server
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: feature_results

    - name: Show the feature results
      debug:
        msg: |
          {{ feature_results.updates }
          
