- name: Uninstall an Application with chocolatey
  hosts: 
  tasks:

    - name: Uninstall Google Chrome
      win_chocolatey:
        name: googlechrome
        state: absent

    - name: UNinstall multiple packages
      win_chocolatey:
        name:
        - slack
        - zoom
        - filezilla
        state: absent
