- name: Install an Application with chocolatey
  hosts: 
  tasks:

    - name: Uninstall Google Chrome
      win_chocolatey:
        name: googlechrome
        state: absent

    - name: Install multiple packages
      win_chocolatey:
        name:
        - vlc
        - zoom
        - windirstat
        state: absent
