- name: Upgrade an Application with chocolatey
  hosts: 
  tasks:

    - name: Upgrade Wireshark
      win_chocolatey:
        name: wireshark
        state: latest

    - name: Upgrade multiple packages
      win_chocolatey:
        name:
        - slack
        - zoom
        - filezilla
        state: latest
