- name: Windows Service on Ansible
  hosts: servername
  tasks:
    - name: checking if a service exists
      win_service:
        name: leandroscardua
      register: services_state

    - name: Debug
      debug:
        var: services_state
