- name: Install IIS Server on windows server
  hosts: servername
  tasks:
    - name: Install IIS (Web-Server Role)
      win_feature:
        name:
        - Web-Server
        state: present
      register: win_feature

    - name: Reboot if installing Web-Server feature requires it
      win_reboot:
      when: win_feature.reboot_required
